# colorscheme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo = 'sjl/badwolf'


# cheetsheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
    let g:cheatsheet#cheat_file = '$HOME/.config/nvim/cheetcheet.md'
'''

# filer
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
    nnoremap <C-e> :NERDTreeToggle<CR>
'''


# Auto close 
[[plugins]]
repo = 'cohama/lexima.vim'


# surround parentheses
[[plugins]]
repo = 'tpope/vim-surround'


# Git Plugin
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'


# preview replacement
[[plugins]]
repo = 'markonm/traces.vim'


# function list
[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'vim-scripts/taglist.vim'
hook_add = """
    set tags = tags
    let Tlist_Ctags_Cmd = "/usr/bin/ctags"
    let Tlist_Show_One_File = 1
    let Tlist_Exit_OnlyWindow = 1
    nnoremap <C-a> :Tlist<CR>
"""


# reuse yank registor
[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = """
    nmap p <Plug>(yankround-p)
    xmap p <Plug>(yankround-p)
    nmap P <Plug>(yankround-P)
    nmap gp <Plug>(yankround-gp)
    xmap gp <Plug>(yankround-gp)
    nmap gP <Plug>(yankround-gP)
    nmap <C-p> <Plug>(yankround-prev)
    nmap <C-n> <Plug>(yankround-next)
"""
