# base for completion
[[plugins]]
repo = 'Shougo/dein.vim'
merged = '0'
 

# Language Server Protocol plugin
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = """
    let g:deoplete#enable_at_startup = 1
"""

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

