[[plugins]]
repo = 'Shougo/dein.vim'
merged = '0'
 
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
    let g:cheatsheet#cheat_file = '$HOME/.config/nvim/cheetcheet.md'
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
    nnoremap <C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = """
    let g:deoplete#enable_at_startup = 1
"""

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'vim-scripts/taglist.vim'
hook_add = """
    set tags = tags
    let Tlist_Ctags_Cmd = "/usr/bin/ctags"
    let Tlist_Show_One_File = 1
    let Tlist_Exit_OnlyWindow = 1
    nnoremap <C-a> :Tlist<CR><C-w>x
"""

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = """
    nmap p <Plug>(yankround-p)
    xmap p <Plug>(yankround-p)
    nmap P <Plug>(yankround-P)
    nmap gp <Plug>(yankround-gp)
    xmap gp <Plug>(yankround-gp)
    nmap gP <Plug>(yankround-gP)
    nmap <C-p> <Plug>(yankround-prev)
    nmap <C-n> <Plug>(yankround-next)
"""
